install: dependencies

software = rofi i3lock-fancy termite kvantum-qt5 lxappearance xclip xfce-polkit
background = awesome i3lock compton-tryone-git qt5ct
optional = ttf-roboto spectacle ant-dracula-kvantum-theme-git xorg-xbacklight papirus-icon-theme


dependencies:
	yay -S $(software) $(background) $(optional)
